@echo off
echo Initializing Git repository...
git init
echo Adding files to Git...
git add .
echo Committing files...
git commit -m "Initial commit - version 0.1"
echo Adding remote repository...
git remote add origin https://github.com/Xenonesis/Team-Blitz.git
echo Pushing to remote repository...
git push -u origin main
echo Done!
